service:
  name: backend-nodejs
  app: backend-serverless
  stage: dev

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs12.x
  apiGateway:
    minimumCompressionSize: 1024
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

inputs:
  src: ./
  memory: 512
  timeout: 10
  description: Nodejs / Express backend
  enf:
    DEBUG: 'express:*'
  traffic: 0.2
  region: us-west-1

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello
