service:
  name: serverless-backend

custom:
  plugins:
    - serverless-webpack
    - serverless-dynamodb-local
    - serverless-offline
    - serverless-plugin-optimize
    - serverless-iam-roles-per-function
    - serverless-enable-api-logs
    - serverless-api-compression

  webpack:
    webpackConfig: ./webpack.config.js
    includeModules:
      forceExclude:
        - aws-sdk
    keepOutputDirectory: true
  
  serverless-offline:
    port: 3003
  
  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true 
      heapInitial: 200m
      heapMax: 1g
      migrate: true 
      seed: true 
      convertEmptyValues: true

  serverless-iam-roles-per-function:
    defaultInherit: true

package:
  individually: true 

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-2'}
  apiGateway:
    minimumCompressionSize: 1024
  environment:
     DEBUG: '*'
     NODE_ENV: ${self:provider.stage}
     AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
     TODOS_TABLE: serverless-todos-${self:provider.stage}
     ATTACHMENTS_BUCKET: attachments-url-${self:provider.stage}

functions:
  hello:
    handler: ./hello.handler
    events:
      - http:
          path: hello
          method: get
          integration: lambda-proxy
          cors:
            - origin: '*'
            - allowCredentials: false

  # @TODO Configure this function
  get-todos:
    handler: ./getTodos.handler
    events:
      - http:
          method: get 
          path: todos
          integration: lambda-proxy
          cors:
            - enabled: true
            - origin: '*'
            - headers: 'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'
            - methods: 'PUT,POST,UPDATE'
            - allowCredentials: true
    iamRoleStatementsName: get-todo-role-function
    iamRoleStatements:
      - Effect: Allow 
        Action:
          - dynamodb:Scan
        Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.TODOS_TABLE}

# Start with resources first
Resources:
  # Attachment Bucket created
  AttachmentsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ${self:provider.environment.ATTACHMENTS_BUCKET}
      CorsConfiguration:
        CorsRules:
          -
            AllowedOrigins:
              - '*'
            AllowedHeaders:
              - '*'
            AllowedMethods:
              - GET 
              - PUT 
              - POST 
              - HEAD 
              - DELETE
            MaxAge: 3000

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref AttachmentsBucket
      PolicyDocument: 
        Version: '2012-10-17'
        Statement:
        - Principal: '*'
          Action: 's3:GetObject'
          Effect: Allow
          Resource: arn:aws:s3:::${self:provider.environment.ATTACHMENTS_BUCKET}/*

# Setup Gateway Response Default 4XX
  GatewayResponseDefault4XX:
    Type: AWS::ApiGateway::GatewayResponse
    Properties:
      ResponseParameters:
        gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
        gatewayresponse.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        gatewayresponse.header.Access-Control-Allow-Methods: "'GET,OPTIONS,POST'"
      ResponseType: DEFAULT_4XX
      RestApiId:
        Ref: 'ApiGatewayRestApi'

# Setup DynamoDB table
  TodosDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        -
          AttributeName: todoId
          AttributeType: S
        -
          AttributeName: userId
          AttributeType: S
      KeySchema:
        -
          AttributeName: todoId
          KeyType: HASH
        -
          AttributeName: userId 
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      TableName: ${self:provider.environment.TODOS_TABLE}