services:
    dynamodb:
        image: amazon/dynamodb-local:latest
        ports:
            - 8001:8001
        command: ["-jar", "DynamoDBLocal.jar", "-sharedDb", "-inMemory"]
        environment:
            - DYNAMO_ENDPOINT=http://dynamodb:8000
    serverless:
        build: .
        volumes:
            - .:/usr/src/app
        environment:
            - DEBUG=*
            - AWS_REGION=localhost
            - AWS_ACCESS_KEY_ID=
            - AWS_SECRET_ACCESS_KEY=
        command: npm start
        links: 
            - dynamodb