service:
  name: restapi-serverless

package:
  individually: true 

plugins:
  - serverless-webpack
  - serverless-aws-documentation
  - serverless-reqvalidator-plugin
  - serverless-iam-roles-per-function
  - serverless-dynamodb-local

custom:
  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true 
      migration: true
  
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  
  documentation:
    api:
      info:
        version: v1.0.0
        title: Todo API
        description: Serverless todo app 
    models:
      - name: CreateTodoRequest
        contentType: application/json
        schema: ${file(src/models/validators/create-todo-request.json)}
      - name: UpdateTodoRequest
        contentType: application/json
        schema: ${file(src/models/validators/update-todo-request.json)}

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-2'}
  apiGateway:
    minimumCompressionSize: 1024
  environment:
     DEBUG: '*'
     NODE_ENV: ${self:provider.stage}
     AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
     TODOS_TABLE: serverless-todos-${self:provider.stage}
     ATTACHMENTS_BUCKET: attachments-url-${self:provider.stage}

functions:
  Auth:
    handler: src/lambda/authorization/auth0Authorizer.handler

  GetTodos:
    handler: src/lambda/functions/getTodos.handler
    events:
      - http:
          method: get 
          path: todos
          cors: true
          allowCredentials: true
          authorizer: Auth
    iamRoleStatementsName: get-todo-role-function
    iamRoleStatements:
      - Effect: Allow 
        Action:
          - dynamodb:Scan
        Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.TODOS_TABLE}

  CreateTodo:
    handler: src/lambda/functions/createTodo.handler
    events:
      - http:
          method: post
          path: todos
          cors: true
          authorizer: Auth
          allowCredentials: true
          reqValidatorName: RequestBodyValidator
          documentation:
            summary: Create a new todo item
            description: Create and insert item into todo table
            requestModels:
              'application/json': CreateTodoRequest
    iamRoleStatementsName: create-todo-role-function
    iamRoleStatements:
      - Effect: Allow 
        Action:
          - dynamodb:PutItem
        Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.TODOS_TABLE}     
  
  UpdateTodo:
    handler: src/lambda/functions/updateTodo.handler
    events:
      - http:
          method: patch 
          path: todos/{todoId}
          cors: true
          authorizer: Auth
          allowCredentials: true
          reqValidatorName: RequestBodyValidator
          documentation:
            summary: Update a new todo item
            description: Update and insert item into todo table
            requestModels:
              'application/json': UpdateTodoRequest

  DeleteTodo:
    handler: src/lambda/functions/deleteTodo.handler
    events:
      - http:
          method: delete
          path: todos/{todoId}
          cors: true
          authorizer: Auth
          allowCredentials: true

resources:
  Resources:
    # Attachment Bucket created
    AttachmentsBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:provider.environment.ATTACHMENTS_BUCKET}
        CorsConfiguration:
          CorsRules:
            -
              AllowedOrigins:
                - '*'
              AllowedHeaders:
                - '*'
              AllowedMethods:
                - GET 
                - PUT 
                - POST 
                - HEAD 
                - DELETE
              MaxAge: 3000
    # Create the bucket policy attached to the main bucket
    BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: !Ref AttachmentsBucket
        PolicyDocument: 
          Version: '2012-10-17'
          Statement:
          - Principal: '*'
            Action: 's3:GetObject'
            Effect: Allow
            Resource: arn:aws:s3:::${self:provider.environment.ATTACHMENTS_BUCKET}/*
    # Setup Gateway Response Default 4XX
    GatewayResponseDefault4XX:
      Type: AWS::ApiGateway::GatewayResponse
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
          gatewayresponse.header.Access-Control-Allow-Methods: "'GET,OPTIONS,POST'"
        ResponseType: DEFAULT_4XX
        RestApiId:
          Ref: 'ApiGatewayRestApi'
    # Setup Request Body Validator
    RequestBodyValidator:
      Type: AWS::ApiGateway::RequestValidator
      Properties:
        Name: 'request-body-validator'
        RestApiId:
          Ref: 'ApiGatewayRestApi'
        ValidateRequestBody: true 
        ValidateRequestParameters: false
    # Setup DynamoDB table
    TodosDynamoDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          -
            AttributeName: todoId
            AttributeType: S
          -
            AttributeName: userId
            AttributeType: S
        KeySchema:
          -
            AttributeName: todoId
            KeyType: HASH
          -
            AttributeName: userId 
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:provider.environment.TODOS_TABLE}
