service:
  name: restapi-serverless

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

package:
  individually: true 

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-2'}
  apiGateway:
    minimumCompressionSize: 1024
  environment:
     DEBUG: '*'
     NODE_ENV: ${self:provider.stage}
     AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
     TODOS_TABLE: serverless-todos-${self:provider.stage}
     ATTACHMENTS_BUCKET: attachments-url-${self:provider.stage}

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello

  GetTodos:
    handler: src/lambda/functions/getTodos.handler
    events:
      - http:
          method: get 
          path: todos
          cors: true
  
  CreateTodo:
    handler: src/lambda/functions/createTodo.handler
    events:
      - http:
          method: post
          path: todos
          cors: true
  
  UpdateTodo:
    handler: src/lambda/functions/updateTodo.handler
    events:
      - http:
          method: patch 
          path: todos/{todoId}
          cors: true
  
  DeleteTodo:
    handler: src/lambda/functions/deleteTodo.handler
    events:
      - http:
          method: delete
          path: todos/{todoId}
          cors: true

Resources:
  # Attachment Bucket created
  AttachmentsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ${self:provider.environment.ATTACHMENTS_BUCKET}
      CorsConfiguration:
        CorsRules:
          -
            AllowedOrigins:
              - '*'
            AllowedHeaders:
              - '*'
            AllowedMethods:
              - GET 
              - PUT 
              - POST 
              - HEAD 
              - DELETE
            MaxAge: 3000
  # Create the bucket policy attached to the main bucket
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref AttachmentsBucket
      PolicyDocument: 
        Version: '2012-10-17'
        Statement:
        - Principal: '*'
          Action: 's3:GetObject'
          Effect: Allow
          Resource: arn:aws:s3:::${self:provider.environment.ATTACHMENTS_BUCKET}/*
  # Setup Gateway Response Default 4XX
  GatewayResponseDefault4XX:
    Type: AWS::ApiGateway::GatewayResponse
    Properties:
      ResponseParameters:
        gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
        gatewayresponse.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        gatewayresponse.header.Access-Control-Allow-Methods: "'GET,OPTIONS,POST'"
      ResponseType: DEFAULT_4XX
      RestApiId:
        Ref: 'ApiGatewayRestApi'
  # Setup DynamoDB table
  TodosDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        -
          AttributeName: todoId
          AttributeType: S
        -
          AttributeName: userId
          AttributeType: S
      KeySchema:
        -
          AttributeName: todoId
          KeyType: HASH
        -
          AttributeName: userId 
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      TableName: ${self:provider.environment.TODOS_TABLE}
