service: todos-app-ext-database

custom:
  stage: ${opt:stage, self:provider.stage}
  tableName: ${self:custom.stage}-ext-todos
  userIdIndex: ${self:custom.stage}-ext-userId

provider:
  name: aws
  stage: dev
  region: us-east-1

resources:
  Resources:
    TodosTable:
      Type: AWS::DynamoDB::Table 
      Properties:
        TableName: ${self:custom.tableName}
        AttributeDefinitions:
          - AttributeName: userId 
            AttributeType: S
          - Attributename: todoId 
            AttributeType: S 
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: todoId
            KeyType: range
        GlobalSecondaryIndexes:
          - IndexName: ${self:custom.userIdIndex}
            KeySchema:
              - AttributeName: userId
                KeyType: HASH
            Projection:
              ProjectType: All
        BillingMode: PAY_PER_REQUEST
        StreamSpecification:
          StreamViewType: NEW_IMAGE

  Outputs:
    TodosTableArn:
      Value:
        Fn::GetAtt:
          - TodosTable
          - Arn 
      Export:
        Name: ${self:custom.stage}-ExtTodosTableArn